[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "tests"
via_ir = true
optimizer = true
optimizer-runs = 15_000

solc = "0.8.22"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

remappings = [
    "solmate/=lib/solmate/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "solady/=lib/solady/src/",
    "@LayerZero/=lib/LayerZero-v2/oapp/contracts/",
    "@layerzerolabs/=lib/LayerZero-v2/oapp/node_modules/@layerzerolabs/",
    "@LayerZeroTesting/=lib/devtools/packages/test-devtools-evm-foundry/contracts/",
]
