[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "tests"
via_ir = true
optimizer = true
optimizer-runs = 150
evm_version = "paris"

solc = "0.8.23"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

remappings = [
    "solmate/=lib/solmate/src/",
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    "solady/=lib/solady/src/",
    "@LayerZero/=lib/LayerZero-v2/oapp/contracts/",
    "@LayerZero-Protocol/=lib/LayerZero-v2/protocol/contracts/",
    "@layerzerolabs/=lib/LayerZero-v2/oapp/node_modules/@layerzerolabs/",
    "@LayerZeroTesting/=lib/LayerZero-v2/oapp/test/",
    "solidity-bytes-utils/=lib/LayerZero-v2/oapp/node_modules/solidity-bytes-utils/",
    "@bloom-v2/=lib/bloom-v2/src/",
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}"}