[compiler.solc]
exclude_paths = [
    "node_modules",
    "venv",
    ".venv",
    "lib",
    "script",
    "tests/foundry",
    "certora"
]
include_paths = ["node_modules"]
via_IR = true

evm_version = 'paris'

remappings = [
    "solmate/=lib/solmate/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "solady/=lib/solady/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "@LayerZero/=lib/LayerZero-v2/oapp/contracts/",
    "@layerzerolabs/=lib/LayerZero-v2/oapp/node_modules/@layerzerolabs/",
    "@LayerZeroTesting/=lib/LayerZero-v2/oapp/test/",
    "solidity-bytes-utils/=lib/LayerZero-v2/oapp/node_modules/solidity-bytes-utils/",
]

[compiler.solc.optimizer]
enabled = true
runs = 200

[detectors]
exclude = []
ignore_paths = ["venv", ".venv", "test"]
exclude_paths = ["node_modules", "lib", "script", "certora"]

[testing]
cmd = "anvil"

[testing.anvil]
cmd_args = "--prune-history 100 --transaction-block-keeper 10 --steps-tracing --silent"

[testing.ganache]
cmd_args = "-k paris -q"

[testing.hardhat]
cmd_args = ""
